version: '3'

services:
  app:
    image: node:lts-alpine
    command: >
      sh -c "cd /app &&
             npm install &&
             npm run dev"
    volumes:
      - .:/app
    ports:
      - 2999:3000
